SoundFiles = new Array;
SoundFiles.push(['1-3', 4]);
SoundFiles.push(['1-4-3', 1]);
SoundFiles.push(['1B', 2]);
SoundFiles.push(['1B 6-3', 1]);
SoundFiles.push(['1B F7', 2]);
SoundFiles.push(['1B F7 MYTEAM', 3]);
SoundFiles.push(['1B F8', 1]);
SoundFiles.push(['1B F9', 2]);
SoundFiles.push(['1B G5', 1]);
SoundFiles.push(['1B G6', 1]);
SoundFiles.push(['1B G7', 1]);
SoundFiles.push(['1B G8', 5]);
SoundFiles.push(['1B G9', 3]);
SoundFiles.push(['1B L7', 1]);
SoundFiles.push(['1B L7 MYTEAM', 2]);
SoundFiles.push(['1B L8', 3]);
SoundFiles.push(['1B L9', 1]);
SoundFiles.push(['2B', 2]);
SoundFiles.push(['2B F7', 1]);
SoundFiles.push(['2B F8', 1]);
SoundFiles.push(['2B F9', 1]);
SoundFiles.push(['2B G7', 2]);
SoundFiles.push(['2B G9', 1]);
SoundFiles.push(['2B L7', 1]);
SoundFiles.push(['2B L7 MYTEAM', 1]);
SoundFiles.push(['2B L8', 1]);
SoundFiles.push(['2B L9', 2]);
SoundFiles.push(['2B L9 MYTEAM', 1]);
SoundFiles.push(['3-1', 1]);
SoundFiles.push(['3B', 1]);
SoundFiles.push(['3B F7', 1]);
SoundFiles.push(['3B G9', 1]);
SoundFiles.push(['3U', 1]);
SoundFiles.push(['4-1', 1]);
SoundFiles.push(['4-3', 2]);
SoundFiles.push(['4-3 O3', 1]);
SoundFiles.push(['5-3', 8]);
SoundFiles.push(['6-3', 2]);
SoundFiles.push(['Alternate Play Calls/1B G8', 3]);
SoundFiles.push(['Alternate Play Calls/1B L7', 1]);
SoundFiles.push(['Alternate Play Calls/1B L9 Alt', 1]);
SoundFiles.push(['Alternate Play Calls/1home (not great) alt', 1]);
SoundFiles.push(['Alternate Play Calls/4-3 Old', 1]);
SoundFiles.push(['Alternate Play Calls/6-3 orig', 1]);
SoundFiles.push(['Alternate Play Calls/F7 alt', 1]);
SoundFiles.push(['Alternate Play Calls/GIDP 4-6-3 alt', 1]);
SoundFiles.push(['Alternate Play Calls/K', 1]);
SoundFiles.push(['Alternate Play Calls/L8 alt2', 1]);
SoundFiles.push(['Alternate Play Calls/Out1 alt', 1]);
SoundFiles.push(['Alternate Play Calls/Out3 alt', 1]);
SoundFiles.push(['Average/140', 1]);
SoundFiles.push(['Average/242', 1]);
SoundFiles.push(['Average/249', 1]);
SoundFiles.push(['Average/250', 1]);
SoundFiles.push(['Average/258', 1]);
SoundFiles.push(['Average/268', 1]);
SoundFiles.push(['Average/273', 1]);
SoundFiles.push(['Average/282', 1]);
SoundFiles.push(['Average/310', 1]);
SoundFiles.push(['Average/311', 1]);
SoundFiles.push(['Average/316', 1]);
SoundFiles.push(['Average/323', 1]);
SoundFiles.push(['Average/333', 1]);
SoundFiles.push(['Average/337', 1]);
SoundFiles.push(['Average/350', 1]);
SoundFiles.push(['BA', 1]);
SoundFiles.push(['Batters/_Infante lead', 1]);
SoundFiles.push(['Batters/_Kratz', 1]);
SoundFiles.push(['Batters/_Kratz lead', 1]);
SoundFiles.push(['Batters/_Rollins', 1]);
SoundFiles.push(['Batters/_Rollins Lead', 1]);
SoundFiles.push(['Batters/2016Altherr', 1]);
SoundFiles.push(['Batters/2016Altherr Lead', 1]);
SoundFiles.push(['Batters/2016Asche', 1]);
SoundFiles.push(['Batters/2016Bautista', 1]);
SoundFiles.push(['Batters/2016Bautista Lead', 1]);
SoundFiles.push(['Batters/2016Blanco, A', 1]);
SoundFiles.push(['Batters/2016Bourjos', 1]);
SoundFiles.push(['Batters/2016Burriss', 1]);
SoundFiles.push(['Batters/2016Eickhoff', 1]);
SoundFiles.push(['Batters/2016Escobar, Y', 1]);
SoundFiles.push(['Batters/2016Featherston', 1]);
SoundFiles.push(['Batters/2016Fowler', 1]);
SoundFiles.push(['Batters/2016Franco, M', 2]);
SoundFiles.push(['Batters/2016Francoeur', 1]);
SoundFiles.push(['Batters/2016Francoeur Lead', 1]);
SoundFiles.push(['Batters/2016Galvis', 1]);
SoundFiles.push(['Batters/2016Galvis Lead', 1]);
SoundFiles.push(['Batters/2016Goeddel', 1]);
SoundFiles.push(['Batters/2016Goeddel Lead', 1]);
SoundFiles.push(['Batters/2016Gonzalez, A', 1]);
SoundFiles.push(['Batters/2016Hamels', 1]);
SoundFiles.push(['Batters/2016Hellickson', 1]);
SoundFiles.push(['Batters/2016Hellickson Lead', 1]);
SoundFiles.push(['Batters/2016Hernandez, C', 1]);
SoundFiles.push(['Batters/2016Herrera', 2]);
SoundFiles.push(['Batters/2016Howard', 1]);
SoundFiles.push(['Batters/2016Howard Lead', 2]);
SoundFiles.push(['Batters/2016Hunter', 1]);
SoundFiles.push(['Batters/2016Jackson, R', 1]);
SoundFiles.push(['Batters/2016Jackson, R Lead', 1]);
SoundFiles.push(['Batters/2016Joseph, T', 2]);
SoundFiles.push(['Batters/2016Joseph, T Lead', 1]);
SoundFiles.push(['Batters/2016Knapp', 2]);
SoundFiles.push(['Batters/2016Lind', 1]);
SoundFiles.push(['Batters/2016Lough Lead', 1]);
SoundFiles.push(['Batters/2016McCann, B', 1]);
SoundFiles.push(['Batters/2016McCutchen', 1]);
SoundFiles.push(['Batters/2016Moore, L', 1]);
SoundFiles.push(['Batters/2016Nina', 1]);
SoundFiles.push(['Batters/2016Paredes Lead', 1]);
SoundFiles.push(['Batters/2016Pujols', 1]);
SoundFiles.push(['Batters/2016Rasmus, C', 1]);
SoundFiles.push(['Batters/2016Ruf', 1]);
SoundFiles.push(['Batters/2016Ruiz', 2]);
SoundFiles.push(['Batters/2016Ruiz Lead', 1]);
SoundFiles.push(['Batters/2016Rupp', 1]);
SoundFiles.push(['Batters/2016Saunders', 2]);
SoundFiles.push(['Batters/2016Smith, S', 2]);
SoundFiles.push(['Batters/2016Stassi', 1]);
SoundFiles.push(['Batters/2016Sweeney', 1]);
SoundFiles.push(['Batters/2016Tulowitzki', 2]);
SoundFiles.push(['Batters/2016Utley', 1]);
SoundFiles.push(['Batters/2016Werth', 1]);
SoundFiles.push(['Batters/2016Werth Lead', 1]);
SoundFiles.push(['Batters/2016Young, Cr', 1]);
SoundFiles.push(['Batters/2016Zimmerman', 1]);
SoundFiles.push(['Batters/Retired/_Barajas', 1]);
SoundFiles.push(['Batters/Retired/_Barmes', 1]);
SoundFiles.push(['Batters/Retired/_Barmes Lead', 1]);
SoundFiles.push(['Batters/Retired/_Dobbs', 1]);
SoundFiles.push(['Batters/Retired/_Ibanez', 1]);
SoundFiles.push(['Batters/Retired/_Ibanez alt', 1]);
SoundFiles.push(['Batters/Retired/_Ibanez Lead', 1]);
SoundFiles.push(['Batters/Retired/_Jones, G', 1]);
SoundFiles.push(['Batters/Retired/_Mather', 1]);
SoundFiles.push(['Batters/Retired/_Mayberry', 1]);
SoundFiles.push(['Batters/Retired/_Soriano, A', 1]);
SoundFiles.push(['Batters/Retired/_Stewart, I', 1]);
SoundFiles.push(['Batters/Retired/_Victorino', 1]);
SoundFiles.push(['Batters/Retired/_Victorino alt', 1]);
SoundFiles.push(['Batters/Retired/Aaron Cook', 1]);
SoundFiles.push(['Batters/Retired/Aaron Matthews', 1]);
SoundFiles.push(['Batters/Retired/Adam Dunn', 1]);
SoundFiles.push(['Batters/Retired/Aramis Ramirez', 1]);
SoundFiles.push(['Batters/Retired/Austin Kearns', 1]);
SoundFiles.push(['Batters/Retired/Brad Hawpe', 1]);
SoundFiles.push(['Batters/Retired/Brad Hawpe alt', 1]);
SoundFiles.push(['Batters/Retired/Brandon Ryan', 1]);
SoundFiles.push(['Batters/Retired/Brian Giles', 1]);
SoundFiles.push(['Batters/Retired/Brian Giles Lead', 2]);
SoundFiles.push(['Batters/Retired/Casey Kotchman', 1]);
SoundFiles.push(['Batters/Retired/Chris Coste', 1]);
SoundFiles.push(['Batters/Retired/Chris Duncan', 1]);
SoundFiles.push(['Batters/Retired/Cristian Guzman', 1]);
SoundFiles.push(['Batters/Retired/Daryle Ward', 1]);
SoundFiles.push(['Batters/Retired/Dmitri Young', 1]);
SoundFiles.push(['Batters/Retired/Eric Bruntlett', 1]);
SoundFiles.push(['Batters/Retired/Garrett Atkins', 1]);
SoundFiles.push(['Batters/Retired/Geoff Jenkins', 1]);
SoundFiles.push(['Batters/Retired/Geoff Jenkins Lead', 1]);
SoundFiles.push(['Batters/Retired/Jair Jurrjens', 1]);
SoundFiles.push(['Batters/Retired/Jason Donald', 1]);
SoundFiles.push(['Batters/Retired/Jason Donald Lead', 1]);
SoundFiles.push(['Batters/Retired/Jason Ellison Lead', 1]);
SoundFiles.push(['Batters/Retired/Jason LaRue', 1]);
SoundFiles.push(['Batters/Retired/Jason LaRue Lead', 1]);
SoundFiles.push(['Batters/Retired/Jesus Flores', 1]);
SoundFiles.push(['Batters/Retired/Jim Edmonds', 1]);
SoundFiles.push(['Batters/Retired/Joe Thurston', 1]);
SoundFiles.push(['Batters/Retired/John Mayberry alt', 1]);
SoundFiles.push(['Batters/Retired/John McDonald', 1]);
SoundFiles.push(['Batters/Retired/Josh Bard', 1]);
SoundFiles.push(['Batters/Retired/Josh Bard Lead', 1]);
SoundFiles.push(['Batters/Retired/Josh Willingham', 1]);
SoundFiles.push(['Batters/Retired/Justin Maxwell', 1]);
SoundFiles.push(['Batters/Retired/Kelly Johnson', 1]);
SoundFiles.push(['Batters/Retired/Kelly Johnson alt', 1]);
SoundFiles.push(['Batters/Retired/Kevin Kouzmanoff', 1]);
SoundFiles.push(['Batters/Retired/Kevin Kouzmanoff Lead', 1]);
SoundFiles.push(['Batters/Retired/Khalil Greene', 1]);
SoundFiles.push(['Batters/Retired/Khalil Greene Lead', 1]);
SoundFiles.push(['Batters/Retired/Kosuke Fukudome', 1]);
SoundFiles.push(['Batters/Retired/Lyle Overbay', 1]);
SoundFiles.push(['Batters/Retired/MacInulty', 1]);
SoundFiles.push(['Batters/Retired/Marco Scutaro Lead', 1]);
SoundFiles.push(['Batters/Retired/Marcus Giles', 1]);
SoundFiles.push(['Batters/Retired/Matt Stairs', 1]);
SoundFiles.push(['Batters/Retired/Miguel Cairo', 1]);
SoundFiles.push(['Batters/Retired/Nick Johnson', 1]);
SoundFiles.push(['Batters/Retired/Pablo Ozuna', 1]);
SoundFiles.push(['Batters/Retired/Pedro Feliz', 1]);
SoundFiles.push(['Batters/Retired/Pedro Feliz Lead', 1]);
SoundFiles.push(['Batters/Retired/Raul Chavez', 1]);
SoundFiles.push(['Batters/Retired/Rick Ankiel', 1]);
SoundFiles.push(['Batters/Retired/Ronnie Belliard', 1]);
SoundFiles.push(['Batters/Retired/Ronnie Belliard Lead', 1]);
SoundFiles.push(['Batters/Retired/Ryan Ludwig Lead', 1]);
SoundFiles.push(['Batters/Retired/Ryan Spilborghs', 1]);
SoundFiles.push(['Batters/Retired/Scott Hairston', 1]);
SoundFiles.push(['Batters/Retired/Tadahito Iguchi', 1]);
SoundFiles.push(['Batters/Retired/Todd Helton', 1]);
SoundFiles.push(['Batters/Retired/Tony Clark', 1]);
SoundFiles.push(['Batters/Retired/Travis Snider', 1]);
SoundFiles.push(['Batters/Retired/Travis Snider Lead', 1]);
SoundFiles.push(['Batters/Retired/Tyler Greene', 1]);
SoundFiles.push(['Batters/Retired/Vernon Wells', 1]);
SoundFiles.push(['Batters/Retired/Willie Harris', 1]);
SoundFiles.push(['BB', 9]);
SoundFiles.push(['BB 4', 4]);
SoundFiles.push(['BB High', 1]);
SoundFiles.push(['BB Inside', 1]);
SoundFiles.push(['Beginning of inning (not coded)/4Bottom', 3]);
SoundFiles.push(['Beginning of inning (not coded)/4Bottom 2-1', 1]);
SoundFiles.push(['Beginning of inning (not coded)/4Bottom 2-1 Boston Red Sox', 1]);
SoundFiles.push(['Beginning of inning (not coded)/4Bottom 2-1 Pittsburgh Pirates', 1]);
SoundFiles.push(['Bell', 1]);
SoundFiles.push(['BI', 1]);
SoundFiles.push(['BK', 1]);
SoundFiles.push(['Count/0-1', 3]);
SoundFiles.push(['Count/0-1 Called', 2]);
SoundFiles.push(['Count/0-1 Called FT', 1]);
SoundFiles.push(['Count/0-1 Called SI', 1]);
SoundFiles.push(['Count/0-1 Foul', 4]);
SoundFiles.push(['Count/0-1 Foul Bunt', 1]);
SoundFiles.push(['Count/0-1 Swinging', 2]);
SoundFiles.push(['Count/0-1 Swinging SI', 1]);
SoundFiles.push(['Count/0-2', 4]);
SoundFiles.push(['Count/0-2 Called', 1]);
SoundFiles.push(['Count/0-2 Foul', 6]);
SoundFiles.push(['Count/0-2 Foul X', 2]);
SoundFiles.push(['Count/0-2 Swinging', 1]);
SoundFiles.push(['Count/0-2 Swinging SI', 1]);
SoundFiles.push(['Count/1-0', 6]);
SoundFiles.push(['Count/1-0 Ball High', 4]);
SoundFiles.push(['Count/1-0 Ball High FT', 1]);
SoundFiles.push(['Count/1-0 Ball High Very', 1]);
SoundFiles.push(['Count/1-0 Ball Inside', 4]);
SoundFiles.push(['Count/1-0 Ball Inside Very', 1]);
SoundFiles.push(['Count/1-0 Ball Low', 6]);
SoundFiles.push(['Count/1-0 Ball Low Dirt', 1]);
SoundFiles.push(['Count/1-0 Ball Low Inside', 2]);
SoundFiles.push(['Count/1-0 Ball Low Outside', 2]);
SoundFiles.push(['Count/1-0 Ball Low SI', 1]);
SoundFiles.push(['Count/1-0 Ball Outside', 3]);
SoundFiles.push(['Count/1-1', 3]);
SoundFiles.push(['Count/1-1 Ball High', 3]);
SoundFiles.push(['Count/1-1 Ball High FT', 1]);
SoundFiles.push(['Count/1-1 Ball High Outside', 1]);
SoundFiles.push(['Count/1-1 Ball Inside', 3]);
SoundFiles.push(['Count/1-1 Ball Low', 2]);
SoundFiles.push(['Count/1-1 Ball Outside', 4]);
SoundFiles.push(['Count/1-1 Called', 1]);
SoundFiles.push(['Count/1-1 Called CU', 1]);
SoundFiles.push(['Count/1-1 Foul', 5]);
SoundFiles.push(['Count/1-1 Foul Bunt', 1]);
SoundFiles.push(['Count/1-1 Swinging', 1]);
SoundFiles.push(['Count/1-1 Swinging CH', 1]);
SoundFiles.push(['Count/1-1 Swinging CU', 1]);
SoundFiles.push(['Count/1-2', 5]);
SoundFiles.push(['Count/1-2 Ball High', 1]);
SoundFiles.push(['Count/1-2 Ball High Inside', 1]);
SoundFiles.push(['Count/1-2 Ball High Inside FT', 1]);
SoundFiles.push(['Count/1-2 Ball High Very', 2]);
SoundFiles.push(['Count/1-2 Ball Inside', 3]);
SoundFiles.push(['Count/1-2 Ball Inside Very', 1]);
SoundFiles.push(['Count/1-2 Ball Low', 2]);
SoundFiles.push(['Count/1-2 Ball Low Dirt', 2]);
SoundFiles.push(['Count/1-2 Ball Low Dirt CU', 1]);
SoundFiles.push(['Count/1-2 Ball Low Outside', 1]);
SoundFiles.push(['Count/1-2 Ball Outside', 1]);
SoundFiles.push(['Count/1-2 Ball Outside FT', 1]);
SoundFiles.push(['Count/1-2 Called', 1]);
SoundFiles.push(['Count/1-2 Foul', 6]);
SoundFiles.push(['Count/1-2 Foul Bunt', 1]);
SoundFiles.push(['Count/1-2 Foul Tip', 1]);
SoundFiles.push(['Count/1-2 Foul X', 1]);
SoundFiles.push(['Count/1-2 Swinging', 2]);
SoundFiles.push(['Count/2-0', 5]);
SoundFiles.push(['Count/2-0 Ball', 1]);
SoundFiles.push(['Count/2-0 Ball High', 2]);
SoundFiles.push(['Count/2-0 Ball High Inside Very', 1]);
SoundFiles.push(['Count/2-0 Ball Inside', 2]);
SoundFiles.push(['Count/2-0 Ball Low', 2]);
SoundFiles.push(['Count/2-0 Ball Low Dirt', 1]);
SoundFiles.push(['Count/2-0 Ball Low Outside', 1]);
SoundFiles.push(['Count/2-0 Ball Outside', 2]);
SoundFiles.push(['Count/2-1', 5]);
SoundFiles.push(['Count/2-1 Ball High', 8]);
SoundFiles.push(['Count/2-1 Ball High Inside', 1]);
SoundFiles.push(['Count/2-1 Ball High Inside CU', 1]);
SoundFiles.push(['Count/2-1 Ball Inside', 2]);
SoundFiles.push(['Count/2-1 Ball Inside Very', 1]);
SoundFiles.push(['Count/2-1 Ball Low', 2]);
SoundFiles.push(['Count/2-1 Ball Low Dirt', 1]);
SoundFiles.push(['Count/2-1 Ball Low Inside', 1]);
SoundFiles.push(['Count/2-1 Ball Outside', 2]);
SoundFiles.push(['Count/2-1 Ball Outside Very', 1]);
SoundFiles.push(['Count/2-1 Called', 3]);
SoundFiles.push(['Count/2-1 Foul', 2]);
SoundFiles.push(['Count/2-1 Swinging', 2]);
SoundFiles.push(['Count/2-2', 5]);
SoundFiles.push(['Count/2-2 Ball High', 2]);
SoundFiles.push(['Count/2-2 Ball High FT', 1]);
SoundFiles.push(['Count/2-2 Ball Inside CH', 1]);
SoundFiles.push(['Count/2-2 Ball Inside FT', 1]);
SoundFiles.push(['Count/2-2 Ball Low', 3]);
SoundFiles.push(['Count/2-2 Ball Low Dirt', 2]);
SoundFiles.push(['Count/2-2 Ball Low Inside', 2]);
SoundFiles.push(['Count/2-2 Ball Low Outside', 1]);
SoundFiles.push(['Count/2-2 Ball Outside', 2]);
SoundFiles.push(['Count/2-2 Called', 1]);
SoundFiles.push(['Count/2-2 Called FT', 1]);
SoundFiles.push(['Count/2-2 Foul', 1]);
SoundFiles.push(['Count/2-2 Foul Bunt', 1]);
SoundFiles.push(['Count/2-2 Foul X', 1]);
SoundFiles.push(['Count/2-2 Swinging', 1]);
SoundFiles.push(['Count/2-2 Swinging FT', 1]);
SoundFiles.push(['Count/3-0', 7]);
SoundFiles.push(['Count/3-0 Ball High', 1]);
SoundFiles.push(['Count/3-0 Ball Inside', 1]);
SoundFiles.push(['Count/3-0 Ball Low', 2]);
SoundFiles.push(['Count/3-0 Ball Low Outside', 1]);
SoundFiles.push(['Count/3-1', 9]);
SoundFiles.push(['Count/3-1 Ball High', 1]);
SoundFiles.push(['Count/3-1 Ball High Outside', 1]);
SoundFiles.push(['Count/3-1 Ball High Very', 1]);
SoundFiles.push(['Count/3-1 Ball Inside', 1]);
SoundFiles.push(['Count/3-1 Ball Low', 1]);
SoundFiles.push(['Count/3-1 Ball Outside', 2]);
SoundFiles.push(['Count/3-1 Called', 1]);
SoundFiles.push(['Count/3-1 Called FT', 1]);
SoundFiles.push(['Count/3-1 Foul', 1]);
SoundFiles.push(['Count/3-1 Low Inside', 1]);
SoundFiles.push(['Count/3-2', 6]);
SoundFiles.push(['Count/3-2 Ball', 1]);
SoundFiles.push(['Count/3-2 Ball High', 2]);
SoundFiles.push(['Count/3-2 Ball High Outside', 1]);
SoundFiles.push(['Count/3-2 Ball Inside', 1]);
SoundFiles.push(['Count/3-2 Ball Low', 1]);
SoundFiles.push(['Count/3-2 Ball Low Dirt', 3]);
SoundFiles.push(['Count/3-2 Ball Outside', 3]);
SoundFiles.push(['Count/3-2 Called', 2]);
SoundFiles.push(['Count/3-2 Foul', 5]);
SoundFiles.push(['Count/3-2 Foul FT', 1]);
SoundFiles.push(['Count/3-2 Foul X', 1]);
SoundFiles.push(['CS', 1]);
SoundFiles.push(['DP 1-2-3', 1]);
SoundFiles.push(['DP 5-4-3', 1]);
SoundFiles.push(['DP 6-4', 1]);
SoundFiles.push(['DS2', 1]);
SoundFiles.push(['E', 1]);
SoundFiles.push(['E5', 1]);
SoundFiles.push(['E6', 1]);
SoundFiles.push(['F7', 6]);
SoundFiles.push(['F7 MYTEAM', 1]);
SoundFiles.push(['F8', 6]);
SoundFiles.push(['F8 O1', 1]);
SoundFiles.push(['F9', 9]);
SoundFiles.push(['F9 O1', 1]);
SoundFiles.push(['FC', 1]);
SoundFiles.push(['FC 3-4', 1]);
SoundFiles.push(['FC 5-6-4', 1]);
SoundFiles.push(['FC 6-4', 1]);
SoundFiles.push(['FC 6-5', 1]);
SoundFiles.push(['FC 9-4', 1]);
SoundFiles.push(['GameOver Atlanta Braves', 1]);
SoundFiles.push(['GameOver Boston Red Sox', 1]);
SoundFiles.push(['GameOver Colorado Rockies', 1]);
SoundFiles.push(['GameOver Florida Marlins', 1]);
SoundFiles.push(['GameOver Houston Astros', 1]);
SoundFiles.push(['GameOver New York Mets', 1]);
SoundFiles.push(['GameOver Philadelphia Phillies', 2]);
SoundFiles.push(['GameOver Philadelphia Phillies 11-10', 1]);
SoundFiles.push(['GameOver Philadelphia Phillies 2-1', 1]);
SoundFiles.push(['GameOver Philadelphia Phillies 5-3', 2]);
SoundFiles.push(['GameOver Philadelphia Phillies 8-7', 1]);
SoundFiles.push(['GameOver Pittsburgh Pirates', 1]);
SoundFiles.push(['GameOver San Diego Padres', 1]);
SoundFiles.push(['GameOver Washington Nationals', 1]);
SoundFiles.push(['GameOver Washington Nationals 1-0', 1]);
SoundFiles.push(['GameOver Washington Nationals 11-6', 1]);
SoundFiles.push(['GIDP 1-2-3', 1]);
SoundFiles.push(['GIDP 1-6-3', 1]);
SoundFiles.push(['GIDP 4-3', 1]);
SoundFiles.push(['GIDP 4-6-3', 1]);
SoundFiles.push(['GIDP 5-4-3', 1]);
SoundFiles.push(['GIDP 6-3', 1]);
SoundFiles.push(['GIDP 6-4', 1]);
SoundFiles.push(['GIDP 6-4-3', 2]);
SoundFiles.push(['GRD', 1]);
SoundFiles.push(['GRD F7', 1]);
SoundFiles.push(['HBP', 2]);
SoundFiles.push(['HighHopes', 1]);
SoundFiles.push(['HomeOut', 1]);
SoundFiles.push(['HR', 1]);
SoundFiles.push(['HR 7', 4]);
SoundFiles.push(['HR 7 MYTEAM', 1]);
SoundFiles.push(['HR 8', 1]);
SoundFiles.push(['HR 9', 3]);
SoundFiles.push(['IBB', 3]);
SoundFiles.push(['Inning/10away', 1]);
SoundFiles.push(['Inning/10away B 7-7', 1]);
SoundFiles.push(['Inning/10home', 1]);
SoundFiles.push(['Inning/10home B', 1]);
SoundFiles.push(['Inning/10home B 7-7', 1]);
SoundFiles.push(['Inning/11away', 1]);
SoundFiles.push(['Inning/11home', 1]);
SoundFiles.push(['Inning/12away', 1]);
SoundFiles.push(['Inning/1away E', 1]);
SoundFiles.push(['Inning/1away E 0-0 Washington Nationals Philadelphia Phillies', 2]);
SoundFiles.push(['Inning/1away E 2-0 Chicago Cubs', 1]);
SoundFiles.push(['Inning/1away E 3-0 Philadelphia Phillies Cincinnati Reds', 1]);
SoundFiles.push(['Inning/1away E 5-0 Washington Nationals Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/1home 2-0 Chicago Cubs', 1]);
SoundFiles.push(['Inning/1home B', 1]);
SoundFiles.push(['Inning/1home E', 3]);
SoundFiles.push(['Inning/1home E 0-0', 1]);
SoundFiles.push(['Inning/1home E 1-0 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/1home E 3-2 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/1home E 5-0 Washington Nationals Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/2away', 1]);
SoundFiles.push(['Inning/2away 2-0 Chicago Cubs', 1]);
SoundFiles.push(['Inning/2away B', 1]);
SoundFiles.push(['Inning/2away B 1-0 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/2away B 3-2 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/2away E', 2]);
SoundFiles.push(['Inning/2away E 0-0 Philadelphia Phillies Washington Nationals', 1]);
SoundFiles.push(['Inning/2away E 1-0 Philadelphia Phillies Washington Nationals', 1]);
SoundFiles.push(['Inning/2away E 2-0 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/2away E 3-2 Philadelphia Phillies Cincinnati Reds', 1]);
SoundFiles.push(['Inning/2home B', 3]);
SoundFiles.push(['Inning/2home B 1-0 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/2home E', 3]);
SoundFiles.push(['Inning/2home E 0-0 Philadelphia Phillies Washington Nationals', 1]);
SoundFiles.push(['Inning/2home E 0-0 Washington Nationals Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/2home E 1-0 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/2home E 2-0 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/2home E 5-0 Washington Nationals', 1]);
SoundFiles.push(['Inning/3away 2-0 Chicago Cubs', 1]);
SoundFiles.push(['Inning/3away B', 3]);
SoundFiles.push(['Inning/3away B 1-0 Philadelphia Phillies', 2]);
SoundFiles.push(['Inning/3home', 1]);
SoundFiles.push(['Inning/3home 2-0 Chicago Cubs', 1]);
SoundFiles.push(['Inning/3home B', 8]);
SoundFiles.push(['Inning/3home B 0-0', 1]);
SoundFiles.push(['Inning/3home B 1-0 Philadelphia Phillies', 2]);
SoundFiles.push(['Inning/3home B 2-0 Philadelphia Phillies New York Mets', 1]);
SoundFiles.push(['Inning/3home B 5-0 Washington Nationals', 1]);
SoundFiles.push(['Inning/3home B 5-2 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/3home E', 2]);
SoundFiles.push(['Inning/3home E 0-0', 1]);
SoundFiles.push(['Inning/3home E 1-0 Philadelphia Phillies', 2]);
SoundFiles.push(['Inning/3home E 5-0 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/3home E 5-1 Washington Nationals', 1]);
SoundFiles.push(['Inning/3home E 5-2 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/4away', 4]);
SoundFiles.push(['Inning/4away 1-0 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/4away 2-0 Minnesota Twins', 1]);
SoundFiles.push(['Inning/4away 2-1 Boston Red Sox Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/4away 2-1 Pittsburgh Pirates Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/4home', 1]);
SoundFiles.push(['Inning/4home 2-1 Pittsburgh Pirates Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/5away', 1]);
SoundFiles.push(['Inning/5home', 1]);
SoundFiles.push(['Inning/6away', 1]);
SoundFiles.push(['Inning/6home', 1]);
SoundFiles.push(['Inning/7away', 1]);
SoundFiles.push(['Inning/7away 5-3 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/7away B', 1]);
SoundFiles.push(['Inning/7away B 1-0 Washington Nationals', 1]);
SoundFiles.push(['Inning/7away B 6-6', 1]);
SoundFiles.push(['Inning/7away E', 5]);
SoundFiles.push(['Inning/7away E 1-0 Washington Nationals', 1]);
SoundFiles.push(['Inning/7away E 8-5 Philadelphia Phillies New York Mets', 1]);
SoundFiles.push(['Inning/7home', 1]);
SoundFiles.push(['Inning/7home 5-3 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/7home B 6-3 Washington Nationals', 1]);
SoundFiles.push(['Inning/8away', 1]);
SoundFiles.push(['Inning/8away B', 4]);
SoundFiles.push(['Inning/8away B 1-0 Washington Nationals', 1]);
SoundFiles.push(['Inning/8away B 1-1', 1]);
SoundFiles.push(['Inning/8away B 6-6', 1]);
SoundFiles.push(['Inning/8away B 7-6 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/8away B 8-5 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/8away E', 1]);
SoundFiles.push(['Inning/8away E 6-6', 1]);
SoundFiles.push(['Inning/8home', 1]);
SoundFiles.push(['Inning/8home B', 6]);
SoundFiles.push(['Inning/8home B 1-0', 1]);
SoundFiles.push(['Inning/8home B 1-0 Washington Nationals', 1]);
SoundFiles.push(['Inning/8home B 10-8 New York Mets', 1]);
SoundFiles.push(['Inning/8home B 1-1', 1]);
SoundFiles.push(['Inning/8home B 5-2 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/9away', 1]);
SoundFiles.push(['Inning/9away B', 9]);
SoundFiles.push(['Inning/9away B 1-0 Washington Nationals', 1]);
SoundFiles.push(['Inning/9away B 1-0 Washington Nationals Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/9away B 10-9 New York Mets', 1]);
SoundFiles.push(['Inning/9away B 10-9 New York Yankees', 1]);
SoundFiles.push(['Inning/9away B 5-2  Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/9away B 5-2 Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/9away B 6-6', 2]);
SoundFiles.push(['Inning/9away B 6-6 Philadelphia Phillies Washington Nationals', 1]);
SoundFiles.push(['Inning/9away B 6-6 Washington Nationals Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/9away B 7-7', 1]);
SoundFiles.push(['Inning/9home', 1]);
SoundFiles.push(['Inning/9home B', 4]);
SoundFiles.push(['Inning/9home B 10-9 New York Mets Philadelphia Phillies', 1]);
SoundFiles.push(['Inning/9home B 11-6 Washington Nationals', 1]);
SoundFiles.push(['Inning/9home B 7-7', 1]);
SoundFiles.push(['Inning/extra innings', 1]);
SoundFiles.push(['InPlay', 1]);
SoundFiles.push(['K', 3]);
SoundFiles.push(['K Foul Tip', 1]);
SoundFiles.push(['K Foul Tip MYTEAM', 1]);
SoundFiles.push(['K MYTEAM', 5]);
SoundFiles.push(['K..', 1]);
SoundFiles.push(['L3', 1]);
SoundFiles.push(['L4', 1]);
SoundFiles.push(['L6', 1]);
SoundFiles.push(['L7', 4]);
SoundFiles.push(['L8', 3]);
SoundFiles.push(['L9', 2]);
SoundFiles.push(['L9 MYTEAM', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Altherr', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Altherr Lead', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Asche', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Blanco, A', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Eickhoff', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Featherston', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Franco, M', 2]);
SoundFiles.push(['NEUTRAL/Batters/2016Galvis', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Galvis Lead', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Hellickson', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Hellickson Lead', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Hernandez, C', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Herrera', 2]);
SoundFiles.push(['NEUTRAL/Batters/2016Howard', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Joseph, T', 2]);
SoundFiles.push(['NEUTRAL/Batters/2016Joseph, T Lead', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Paredes Lead', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Ruiz', 1]);
SoundFiles.push(['NEUTRAL/Batters/2016Rupp', 1]);
SoundFiles.push(['NEUTRAL/Inning/4away', 1]);
SoundFiles.push(['NEUTRAL/Inning/7away', 1]);
SoundFiles.push(['NEUTRAL/Inning/7home', 1]);
SoundFiles.push(['Out1', 10]);
SoundFiles.push(['Out1 I2', 1]);
SoundFiles.push(['Out1 I3', 2]);
SoundFiles.push(['Out1 I7', 3]);
SoundFiles.push(['Out1 I8', 2]);
SoundFiles.push(['Out2', 10]);
SoundFiles.push(['Out2 I7', 1]);
SoundFiles.push(['Out2 I9', 1]);
SoundFiles.push(['Out3', 1]);
SoundFiles.push(['Out3 Atlanta Braves', 1]);
SoundFiles.push(['Out3 Chicago Cubs', 1]);
SoundFiles.push(['Out3 Colorado Rockies', 1]);
SoundFiles.push(['Out3 Florida Marlins', 1]);
SoundFiles.push(['Out3 Houston Astros', 1]);
SoundFiles.push(['Out3 Miami Marlins', 1]);
SoundFiles.push(['Out3 Minnesota Twins', 1]);
SoundFiles.push(['Out3 New York Mets', 3]);
SoundFiles.push(['Out3 Philadelphia Phillies', 7]);
SoundFiles.push(['Out3 Philadelphia Phillies I1', 1]);
SoundFiles.push(['Out3 Philadelphia Phillies I2', 1]);
SoundFiles.push(['Out3 Philadelphia Phillies I3', 1]);
SoundFiles.push(['Out3 Philadelphia Phillies I8', 4]);
SoundFiles.push(['Out3 Pittsburgh Pirates', 1]);
SoundFiles.push(['Out3 San Diego Padres', 1]);
SoundFiles.push(['Out3 St. Louis Cardinals', 1]);
SoundFiles.push(['Out3 Toronto Blue Jays', 1]);
SoundFiles.push(['Out3 Washington Nationals', 2]);
SoundFiles.push(['Out3 Washington Nationals I2', 1]);
SoundFiles.push(['Out3 Washington Nationals I3', 1]);
SoundFiles.push(['P2', 4]);
SoundFiles.push(['P3', 1]);
SoundFiles.push(['P4', 3]);
SoundFiles.push(['P4 O2', 1]);
SoundFiles.push(['P5', 1]);
SoundFiles.push(['P6', 5]);
SoundFiles.push(['P7', 5]);
SoundFiles.push(['P8', 4]);
SoundFiles.push(['P9', 1]);
SoundFiles.push(['PB', 1]);
SoundFiles.push(['PC', 4]);
SoundFiles.push(['PC Cincinnati Reds', 1]);
SoundFiles.push(['PC Florida Marlins', 1]);
SoundFiles.push(['PC Philadelphia Phillies', 4]);
SoundFiles.push(['PC Toronto Blue Jays', 1]);
SoundFiles.push(['PC Washington Nationals', 3]);
SoundFiles.push(['PH', 2]);
SoundFiles.push(['Pitchers/J C Romero', 1]);
SoundFiles.push(['PO', 1]);
SoundFiles.push(['POA 1B', 1]);
SoundFiles.push(['POA 2B', 1]);
SoundFiles.push(['PR', 1]);
SoundFiles.push(['PR 2B', 1]);
SoundFiles.push(['Replay/Challenge', 5]);
SoundFiles.push(['Replay/Challenge Philadelphia Phillies', 2]);
SoundFiles.push(['Replay/Overturned', 2]);
SoundFiles.push(['Replay/Upheld', 1]);
SoundFiles.push(['RHE/0000', 10]);
SoundFiles.push(['RHE/0001', 4]);
SoundFiles.push(['RHE/0100', 2]);
SoundFiles.push(['RHE/0101', 9]);
SoundFiles.push(['RHE/0101 I8 Philadelphia Phillies', 1]);
SoundFiles.push(['RHE/0102', 2]);
SoundFiles.push(['RHE/0103', 4]);
SoundFiles.push(['RHE/0103 Philadelphia Phillies', 1]);
SoundFiles.push(['RHE/0103 Washington Nationals', 1]);
SoundFiles.push(['RHE/0111', 1]);
SoundFiles.push(['RHE/0112', 1]);
SoundFiles.push(['RHE/0201', 1]);
SoundFiles.push(['RHE/0202', 3]);
SoundFiles.push(['RHE/0203', 1]);
SoundFiles.push(['RHE/0212', 1]);
SoundFiles.push(['RHE/1100', 2]);
SoundFiles.push(['RHE/1101', 1]);
SoundFiles.push(['RHE/1102', 1]);
SoundFiles.push(['RHE/1111', 1]);
SoundFiles.push(['RHE/1200', 1]);
SoundFiles.push(['RHE/1201', 2]);
SoundFiles.push(['RHE/1202', 1]);
SoundFiles.push(['RHE/1303', 1]);
SoundFiles.push(['RHE/1402', 1]);
SoundFiles.push(['RHE/2200', 1]);
SoundFiles.push(['RHE/2202', 1]);
SoundFiles.push(['RHE/2222', 1]);
SoundFiles.push(['RHE/2301', 1]);
SoundFiles.push(['RHE/2402', 1]);
SoundFiles.push(['RHE/3201', 1]);
SoundFiles.push(['RHE/3300', 1]);
SoundFiles.push(['RHE/3302', 1]);
SoundFiles.push(['RHE/3402', 1]);
SoundFiles.push(['RHE/4210', 1]);
SoundFiles.push(['RHE/4502', 1]);
SoundFiles.push(['RHE/5511', 2]);
SoundFiles.push(['RHE/5601', 1]);
SoundFiles.push(['RHE/6600', 1]);
SoundFiles.push(['RHE/I123', 2]);
SoundFiles.push(['RHE/I123 I8', 1]);
SoundFiles.push(['Runners/0 O2', 1]);
SoundFiles.push(['Runners/1', 3]);
SoundFiles.push(['Runners/1 O1', 1]);
SoundFiles.push(['Runners/1 O1 8I', 1]);
SoundFiles.push(['Runners/2', 2]);
SoundFiles.push(['Runners/3', 1]);
SoundFiles.push(['Runners/3 O0', 1]);
SoundFiles.push(['Runners/4', 1]);
SoundFiles.push(['Runners/5', 2]);
SoundFiles.push(['Runners/5 O0', 1]);
SoundFiles.push(['Runners/5 O2', 2]);
SoundFiles.push(['Runners/6', 2]);
SoundFiles.push(['Runners/6 O0', 2]);
SoundFiles.push(['Runners/6 O0 I1 home', 1]);
SoundFiles.push(['Runners/6 O2', 1]);
SoundFiles.push(['Runners/7', 5]);
SoundFiles.push(['Runners/7 O0', 2]);
SoundFiles.push(['Runners/7 O1', 1]);
SoundFiles.push(['Runners/7 O2', 4]);
SoundFiles.push(['Runs/Coming in to score', 1]);
SoundFiles.push(['Runs/Coming in to score alt', 1]);
SoundFiles.push(['Runs/It was an RBI', 1]);
SoundFiles.push(['Runs/R1', 1]);
SoundFiles.push(['Runs/R1 2B', 1]);
SoundFiles.push(['Runs/R1 2B MYTEAM', 2]);
SoundFiles.push(['Runs/R1 BB', 1]);
SoundFiles.push(['Runs/R2', 2]);
SoundFiles.push(['Runs/R2 2B', 1]);
SoundFiles.push(['Runs/R2 HR', 2]);
SoundFiles.push(['Runs/R3', 1]);
SoundFiles.push(['Runs/R3 2B', 1]);
SoundFiles.push(['Runs/R3 HR', 1]);
SoundFiles.push(['SAC RBI', 1]);
SoundFiles.push(['SAC_B', 2]);
SoundFiles.push(['SB', 1]);
SoundFiles.push(['Score/0-0', 3]);
SoundFiles.push(['Score/0-0 Philadelphia Phillies Washington Nationals', 2]);
SoundFiles.push(['Score/1-0', 2]);
SoundFiles.push(['Score/1-0 Other Team Philadelphia Phillies', 2]);
SoundFiles.push(['Score/1-0 Philadelphia Phillies', 10]);
SoundFiles.push(['Score/1-0 Washington Nationals', 2]);
SoundFiles.push(['Score/10-10', 1]);
SoundFiles.push(['Score/10-2', 1]);
SoundFiles.push(['Score/10-6', 1]);
SoundFiles.push(['Score/10-6 Washington Nationals', 1]);
SoundFiles.push(['Score/10-8', 1]);
SoundFiles.push(['Score/10-8 New York Mets', 1]);
SoundFiles.push(['Score/10-9', 1]);
SoundFiles.push(['Score/10-9 New York Mets', 2]);
SoundFiles.push(['Score/10-9 New York Yankees', 1]);
SoundFiles.push(['Score/1-1', 5]);
SoundFiles.push(['Score/1-1 Philadelphia Phillies St. Louis Cardinals', 1]);
SoundFiles.push(['Score/11-6', 1]);
SoundFiles.push(['Score/11-6 Washington Nationals', 1]);
SoundFiles.push(['Score/13-1', 1]);
SoundFiles.push(['Score/2-0', 3]);
SoundFiles.push(['Score/2-0 Chicago Cubs', 1]);
SoundFiles.push(['Score/2-0 Other Team Philadelphia Phillies', 1]);
SoundFiles.push(['Score/2-0 Philadelphia Phillies', 4]);
SoundFiles.push(['Score/2-0 Philadelphia Phillies New York Mets', 1]);
SoundFiles.push(['Score/2-1 Other Team Philadelphia Phillies', 1]);
SoundFiles.push(['Score/2-1 Philadelphia Phillies', 2]);
SoundFiles.push(['Score/2-2', 1]);
SoundFiles.push(['Score/3-0', 1]);
SoundFiles.push(['Score/3-2', 2]);
SoundFiles.push(['Score/3-2 Philadelphia Phillies', 1]);
SoundFiles.push(['Score/3-2 Philadelphia Phillies Cincinnati Reds', 1]);
SoundFiles.push(['Score/3-3', 1]);
SoundFiles.push(['Score/4-0', 1]);
SoundFiles.push(['Score/4-1 Philadelphia Phillies', 1]);
SoundFiles.push(['Score/4-2', 1]);
SoundFiles.push(['Score/4-2 Philadelphia Phillies', 1]);
SoundFiles.push(['Score/5-0', 2]);
SoundFiles.push(['Score/5-0 Other Team Philadelphia Phillies', 1]);
SoundFiles.push(['Score/5-0 Philadelphia Phillies', 1]);
SoundFiles.push(['Score/5-0 Washington Nationals', 3]);
SoundFiles.push(['Score/5-0 Washington Nationals Philadelphia Phillies', 1]);
SoundFiles.push(['Score/5-1 Other Team Philadelphia Phillies', 1]);
SoundFiles.push(['Score/5-1 Philadelphia Phillies', 1]);
SoundFiles.push(['Score/5-2', 1]);
SoundFiles.push(['Score/5-2 Philadelphia Phillies', 7]);
SoundFiles.push(['Score/5-3 Philadelphia Phillies', 1]);
SoundFiles.push(['Score/5-4', 1]);
SoundFiles.push(['Score/6-1 Philadelphia Phillies', 1]);
SoundFiles.push(['Score/6-2', 1]);
SoundFiles.push(['Score/6-3', 1]);
SoundFiles.push(['Score/6-3 Other Team Philadelphia Phillies', 1]);
SoundFiles.push(['Score/6-3 Washington Nationals Philadelphia Phillies', 1]);
SoundFiles.push(['Score/6-4', 1]);
SoundFiles.push(['Score/6-4 Philadelphia Phillies', 1]);
SoundFiles.push(['Score/6-4 Washington Nationals', 1]);
SoundFiles.push(['Score/6-5', 1]);
SoundFiles.push(['Score/6-6', 4]);
SoundFiles.push(['Score/6-6 Philadelphia Phillies Washington Nationals', 1]);
SoundFiles.push(['Score/7-1 Philadelphia Phillies', 1]);
SoundFiles.push(['Score/7-2', 1]);
SoundFiles.push(['Score/7-3', 1]);
SoundFiles.push(['Score/7-3 Other Team Philadelphia Phillies', 1]);
SoundFiles.push(['Score/7-4 Philadelphia Phillies', 1]);
SoundFiles.push(['Score/7-6', 2]);
SoundFiles.push(['Score/7-6 Philadelphia Phillies', 2]);
SoundFiles.push(['Score/7-6 Philadelphia Phillies Washington Nationals', 1]);
SoundFiles.push(['Score/7-7', 1]);
SoundFiles.push(['Score/8-1', 1]);
SoundFiles.push(['Score/8-1 Philadelphia Phillies', 1]);
SoundFiles.push(['Score/8-2', 1]);
SoundFiles.push(['Score/8-4 Philadelphia Phillies', 1]);
SoundFiles.push(['Score/8-5', 1]);
SoundFiles.push(['Score/8-5 Philadelphia Phillies', 2]);
SoundFiles.push(['Score/8-5 Philadelphia Phillies New York Mets', 1]);
SoundFiles.push(['Score/8-6', 1]);
SoundFiles.push(['Score/8-7', 1]);
SoundFiles.push(['Score/9-1', 1]);
SoundFiles.push(['Score/9-1 Philadelphia Phillies', 1]);
SoundFiles.push(['Score/9-2', 1]);
SoundFiles.push(['Score/9-5', 1]);
SoundFiles.push(['Score/9-5 Other Team Philadelphia Phillies', 1]);
SoundFiles.push(['Score/9-6', 1]);
SoundFiles.push(['Score/9-9', 1]);
SoundFiles.push(['SF 8', 1]);
SoundFiles.push(['Stretch', 1]);
SoundFiles.push(['Stretch Harry', 1]);
SoundFiles.push(['Stretch pre-tune', 1]);
SoundFiles.push(['THEM/1-3', 2]);
SoundFiles.push(['THEM/1-3 O1', 1]);
SoundFiles.push(['THEM/1-3 O1 I9', 1]);
SoundFiles.push(['THEM/1-3 O3 Chicago Cubs', 1]);
SoundFiles.push(['THEM/1-3 O3 Chicago Cubs I2', 1]);
SoundFiles.push(['THEM/1B F9', 1]);
SoundFiles.push(['THEM/1B L7', 1]);
SoundFiles.push(['THEM/1B L8', 4]);
SoundFiles.push(['THEM/2B L7', 1]);
SoundFiles.push(['THEM/4-3', 1]);
SoundFiles.push(['THEM/4-3 O1', 1]);
SoundFiles.push(['THEM/4-3 O1 I4', 1]);
SoundFiles.push(['THEM/Average/273', 1]);
SoundFiles.push(['THEM/Average/282', 1]);
SoundFiles.push(['THEM/Average/316', 1]);
SoundFiles.push(['THEM/BK', 1]);
SoundFiles.push(['THEM/Count/0-1', 1]);
SoundFiles.push(['THEM/Count/0-1 Swinging', 1]);
SoundFiles.push(['THEM/Count/0-2 Foul FT', 1]);
SoundFiles.push(['THEM/Count/0-2 Swinging', 3]);
SoundFiles.push(['THEM/Count/1-0 Ball High', 1]);
SoundFiles.push(['THEM/Count/1-0 Ball Inside', 2]);
SoundFiles.push(['THEM/Count/1-0 Ball Low', 2]);
SoundFiles.push(['THEM/Count/1-0 Ball Low Inside FT', 1]);
SoundFiles.push(['THEM/Count/1-1 Ball High', 1]);
SoundFiles.push(['THEM/Count/1-1 Ball Inside', 1]);
SoundFiles.push(['THEM/Count/1-1 Ball Low', 1]);
SoundFiles.push(['THEM/Count/1-1 Ball Outside', 2]);
SoundFiles.push(['THEM/Count/1-1 Called', 1]);
SoundFiles.push(['THEM/Count/1-1 Foul', 1]);
SoundFiles.push(['THEM/Count/1-1 Swinging', 2]);
SoundFiles.push(['THEM/Count/1-2 Ball High FT', 1]);
SoundFiles.push(['THEM/Count/1-2 Ball Inside FT', 1]);
SoundFiles.push(['THEM/Count/1-2 Ball Low', 1]);
SoundFiles.push(['THEM/Count/1-2 Ball Outside', 1]);
SoundFiles.push(['THEM/Count/1-2 Called', 1]);
SoundFiles.push(['THEM/Count/1-2 Foul', 3]);
SoundFiles.push(['THEM/Count/1-2 Foul X', 1]);
SoundFiles.push(['THEM/Count/1-2 Swinging', 1]);
SoundFiles.push(['THEM/Count/1-2 Swinging CH', 2]);
SoundFiles.push(['THEM/Count/2-0 Ball Outside', 1]);
SoundFiles.push(['THEM/Count/2-1 Ball Inside', 1]);
SoundFiles.push(['THEM/Count/2-1 Ball Low', 1]);
SoundFiles.push(['THEM/Count/2-1 Called', 1]);
SoundFiles.push(['THEM/Count/2-1 Swinging', 1]);
SoundFiles.push(['THEM/Count/2-2 Ball High', 1]);
SoundFiles.push(['THEM/Count/2-2 Ball Outside', 3]);
SoundFiles.push(['THEM/Count/2-2 Called', 1]);
SoundFiles.push(['THEM/Count/2-2 Foul', 2]);
SoundFiles.push(['THEM/Count/2-2 Foul X', 3]);
SoundFiles.push(['THEM/Count/2-2 Swinging', 1]);
SoundFiles.push(['THEM/Count/3-1 Ball High Very', 1]);
SoundFiles.push(['THEM/Count/3-2 Ball', 1]);
SoundFiles.push(['THEM/Count/3-2 Ball Low', 1]);
SoundFiles.push(['THEM/Count/3-2 Ball Low Dirt', 1]);
SoundFiles.push(['THEM/Count/3-2 Ball Outside', 1]);
SoundFiles.push(['THEM/Count/3-2 Ball Outside CH', 1]);
SoundFiles.push(['THEM/Count/3-2 Foul X', 1]);
SoundFiles.push(['THEM/DP 6-3', 1]);
SoundFiles.push(['THEM/F7', 1]);
SoundFiles.push(['THEM/F7 O2', 2]);
SoundFiles.push(['THEM/F8', 1]);
SoundFiles.push(['THEM/F9 O2', 2]);
SoundFiles.push(['THEM/G4', 1]);
SoundFiles.push(['THEM/G4 O1', 1]);
SoundFiles.push(['THEM/G4 O1 I1', 1]);
SoundFiles.push(['THEM/G4 O2', 1]);
SoundFiles.push(['THEM/GameOver Philadelphia Phillies 5-3', 1]);
SoundFiles.push(['THEM/Going to 2nd mistakenly and thrown out', 1]);
SoundFiles.push(['THEM/InPlay', 1]);
SoundFiles.push(['THEM/K', 5]);
SoundFiles.push(['THEM/K.. O1 I4', 1]);
SoundFiles.push(['THEM/L4 O3', 1]);
SoundFiles.push(['THEM/L4 O3 Pittsburgh Pirates', 1]);
SoundFiles.push(['THEM/L8', 1]);
SoundFiles.push(['THEM/Moving up to third base', 1]);
SoundFiles.push(['THEM/Out1', 1]);
SoundFiles.push(['THEM/Out1 I3', 1]);
SoundFiles.push(['THEM/Out1 I4', 1]);
SoundFiles.push(['THEM/Out1 I9', 1]);
SoundFiles.push(['THEM/Out2', 2]);
SoundFiles.push(['THEM/Out3 Chicago Cubs', 1]);
SoundFiles.push(['THEM/Out3 Chicago Cubs I2', 1]);
SoundFiles.push(['THEM/Out3 Minnesota Twins', 1]);
SoundFiles.push(['THEM/Out3 Minnesota Twins I4', 1]);
SoundFiles.push(['THEM/Out3 Toronto Blue Jays', 1]);
SoundFiles.push(['THEM/Out3 Toronto Blue Jays I4', 1]);
SoundFiles.push(['THEM/Out3 Toronto Blue Jays I5', 1]);
SoundFiles.push(['THEM/P7 O2', 1]);
SoundFiles.push(['THEM/P9', 1]);
SoundFiles.push(['THEM/P9 O1', 1]);
SoundFiles.push(['THEM/P9 O1 I8', 1]);
SoundFiles.push(['THEM/POA 1B', 3]);
SoundFiles.push(['THEM/RHE/0000 I7 away', 1]);
SoundFiles.push(['THEM/RHE/0100', 1]);
SoundFiles.push(['THEM/RHE/0100 I4 away', 1]);
SoundFiles.push(['THEM/RHE/0101', 3]);
SoundFiles.push(['THEM/RHE/0101 I4 home 2-1 Pittsburgh Pirates Philadelphia Phillies', 1]);
SoundFiles.push(['THEM/RHE/0101 I5 Toronto Blue Jays', 1]);
SoundFiles.push(['THEM/RHE/0201', 1]);
SoundFiles.push(['THEM/RHE/0201 I4 away', 1]);
SoundFiles.push(['THEM/RHE/0201 I4 away 2-1 Philadelphia Phillies Toronto Blue Jays', 1]);
SoundFiles.push(['THEM/RHE/1201', 1]);
SoundFiles.push(['THEM/RHE/1201 I4 away 2-1 Boston Red Sox Philadelphia Phillies', 1]);
SoundFiles.push(['THEM/RHE/I123', 4]);
SoundFiles.push(['THEM/RHE/I123 I4 away', 1]);
SoundFiles.push(['THEM/RHE/I123 I8 away', 1]);
SoundFiles.push(['THEM/RHE/I123 I8 away 5-3 Philadelphia Phillies', 1]);
SoundFiles.push(['THEM/Runners/0 O1', 1]);
SoundFiles.push(['THEM/Runners/1 O2', 2]);
SoundFiles.push(['THEM/Runners/4 O2', 1]);
SoundFiles.push(['THEM/Score/1-1 I4', 1]);
SoundFiles.push(['THEM/Score/2-0 Chicago Cubs', 1]);
SoundFiles.push(['THEM/Score/2-0 Chicago Cubs I2', 1]);
SoundFiles.push(['THEM/Score/2-0 Chicago Cubs I3 home', 1]);
SoundFiles.push(['THEM/Score/2-0 Minnesota Twins', 1]);
SoundFiles.push(['THEM/Score/2-0 Pittsburgh Pirates', 1]);
SoundFiles.push(['THEM/Score/2-1 Boston Red Sox', 2]);
SoundFiles.push(['THEM/Score/2-1 Boston Red Sox I4', 1]);
SoundFiles.push(['THEM/Score/2-1 Boston Red Sox Philadelphia Phillies', 1]);
SoundFiles.push(['THEM/Score/2-1 Pittsburgh Pirates', 2]);
SoundFiles.push(['THEM/Score/2-1 Pittsburgh Pirates I4 home', 1]);
SoundFiles.push(['THEM/SF 8 RBI', 1]);
SoundFiles.push(['THEM/Strikeouts/3K', 1]);
SoundFiles.push(['THEM/Strikeouts/6K', 1]);
SoundFiles.push(['THEM/Strikeouts/6K I3', 1]);
SoundFiles.push(['US/1B F8', 1]);
SoundFiles.push(['US/1B G8 +', 1]);
SoundFiles.push(['US/1B G9', 1]);
SoundFiles.push(['US/2B G9', 1]);
SoundFiles.push(['US/2B L7', 1]);
SoundFiles.push(['US/6-3', 1]);
SoundFiles.push(['US/Average/290', 1]);
SoundFiles.push(['US/Average/310', 1]);
SoundFiles.push(['US/BB', 1]);
SoundFiles.push(['US/Count/0-1 Called', 1]);
SoundFiles.push(['US/Count/0-1 Called FT', 1]);
SoundFiles.push(['US/Count/0-1 Foul', 3]);
SoundFiles.push(['US/Count/0-2 Foul X', 1]);
SoundFiles.push(['US/Count/0-2 Foul X CU', 1]);
SoundFiles.push(['US/Count/0-2 Swinging', 2]);
SoundFiles.push(['US/Count/1-0 Ball High', 3]);
SoundFiles.push(['US/Count/1-0 Ball High FT', 1]);
SoundFiles.push(['US/Count/1-0 Ball Low', 3]);
SoundFiles.push(['US/Count/1-0 Ball Low Inside', 1]);
SoundFiles.push(['US/Count/1-0 Ball Outside', 1]);
SoundFiles.push(['US/Count/1-1 Ball Inside', 1]);
SoundFiles.push(['US/Count/1-1 Ball Outside', 1]);
SoundFiles.push(['US/Count/1-1 Called', 2]);
SoundFiles.push(['US/Count/1-1 Foul', 3]);
SoundFiles.push(['US/Count/1-1 Foul FT', 1]);
SoundFiles.push(['US/Count/1-1 Swinging', 1]);
SoundFiles.push(['US/Count/1-1 Swinging CU', 1]);
SoundFiles.push(['US/Count/1-2 Ball High FT', 1]);
SoundFiles.push(['US/Count/1-2 Ball Low Outside', 1]);
SoundFiles.push(['US/Count/1-2 Ball Low Very CU', 1]);
SoundFiles.push(['US/Count/1-2 Foul', 2]);
SoundFiles.push(['US/Count/1-2 Foul X FT', 1]);
SoundFiles.push(['US/Count/2-0 Ball Inside', 1]);
SoundFiles.push(['US/Count/2-0 Ball Low', 1]);
SoundFiles.push(['US/Count/2-0 Ball Outside', 1]);
SoundFiles.push(['US/Count/2-0 Called FT', 1]);
SoundFiles.push(['US/Count/2-1 Ball High', 1]);
SoundFiles.push(['US/Count/2-1 Ball Low', 1]);
SoundFiles.push(['US/Count/2-1 Ball Low FT', 1]);
SoundFiles.push(['US/Count/2-1 Ball Outside', 1]);
SoundFiles.push(['US/Count/2-1 Called', 1]);
SoundFiles.push(['US/Count/2-1 Foul', 2]);
SoundFiles.push(['US/Count/2-2 Ball Inside', 1]);
SoundFiles.push(['US/Count/2-2 Ball Low', 1]);
SoundFiles.push(['US/Count/2-2 Called', 1]);
SoundFiles.push(['US/Count/2-2 Foul', 2]);
SoundFiles.push(['US/Count/2-2 Foul FT', 1]);
SoundFiles.push(['US/Count/2-2 Foul X', 1]);
SoundFiles.push(['US/Count/3-1 Ball Outside', 1]);
SoundFiles.push(['US/Count/3-2 Ball Low', 1]);
SoundFiles.push(['US/Count/3-2 Foul', 1]);
SoundFiles.push(['US/Count/3-2 Foul X', 2]);
SoundFiles.push(['US/F9', 1]);
SoundFiles.push(['US/FC 6-4', 1]);
SoundFiles.push(['US/FC 6-4 O3 Philadelphia Phillies', 1]);
SoundFiles.push(['US/G9', 1]);
SoundFiles.push(['US/GameOver Philadelphia Phillies 5-3', 1]);
SoundFiles.push(['US/HBP', 1]);
SoundFiles.push(['US/Hits/6 Philadelphia Phillies', 1]);
SoundFiles.push(['US/Hits/7 Philadelphia Phillies', 1]);
SoundFiles.push(['US/HomeOut', 1]);
SoundFiles.push(['US/HR 8', 2]);
SoundFiles.push(['US/InPlay', 1]);
SoundFiles.push(['US/K', 5]);
SoundFiles.push(['US/K DP CS', 1]);
SoundFiles.push(['US/K O1', 1]);
SoundFiles.push(['US/L6', 1]);
SoundFiles.push(['US/L6 O3', 1]);
SoundFiles.push(['US/L8', 1]);
SoundFiles.push(['US/Out1', 2]);
SoundFiles.push(['US/Out1 I4', 1]);
SoundFiles.push(['US/Out1 I5', 1]);
SoundFiles.push(['US/Out2', 3]);
SoundFiles.push(['US/Out2 I4', 2]);
SoundFiles.push(['US/Out3 Philadelphia Phillies', 1]);
SoundFiles.push(['US/Out3 Philadelphia Phillies I2', 1]);
SoundFiles.push(['US/P2', 1]);
SoundFiles.push(['US/P2 O2', 1]);
SoundFiles.push(['US/P3', 1]);
SoundFiles.push(['US/P8', 2]);
SoundFiles.push(['US/P8 O3 Philadelphia Phillies I4', 1]);
SoundFiles.push(['US/PF3', 1]);
SoundFiles.push(['US/POA 1B', 2]);
SoundFiles.push(['US/RHE/0000', 2]);
SoundFiles.push(['US/RHE/0101', 4]);
SoundFiles.push(['US/RHE/0101 I4 2-1 Philadelphia Phillies', 1]);
SoundFiles.push(['US/RHE/0101 I4 home', 1]);
SoundFiles.push(['US/RHE/0101 I7 home', 1]);
SoundFiles.push(['US/RHE/0201', 1]);
SoundFiles.push(['US/RHE/0201 I4 Philadelphia Phillies', 1]);
SoundFiles.push(['US/RHE/0203 Philadelphia Phillies', 1]);
SoundFiles.push(['US/RHE/1102', 1]);
SoundFiles.push(['US/RHE/I123', 1]);
SoundFiles.push(['US/RHE/I123 I8 Philadelphia Phillies', 1]);
SoundFiles.push(['US/Runners/1 O0', 1]);
SoundFiles.push(['US/Runners/1 O2', 1]);
SoundFiles.push(['US/Runners/5 O0', 2]);
SoundFiles.push(['US/Runners/5 O0 I1', 1]);
SoundFiles.push(['US/Runners/5 O0 I1 Phillies', 1]);
SoundFiles.push(['US/Runners/5 O0 Phillies', 1]);
SoundFiles.push(['US/Runners/6', 1]);
SoundFiles.push(['US/Runners/6 O0', 2]);
SoundFiles.push(['US/Runners/6 O0 Phillies', 1]);
SoundFiles.push(['US/Runners/6 O1', 1]);
SoundFiles.push(['US/Runners/6 O1 I4', 1]);
SoundFiles.push(['US/Runners/7', 2]);
SoundFiles.push(['US/Runners/7 O1', 2]);
SoundFiles.push(['US/Runners/7 O1 Phillies', 1]);
SoundFiles.push(['US/Runners/7 O2', 1]);
SoundFiles.push(['US/Runners/7 O2 I4', 1]);
SoundFiles.push(['US/Runners/7 O2 I4 Phillies', 1]);
SoundFiles.push(['US/Runners/7 O2 Phillies', 1]);
SoundFiles.push(['US/SB', 1]);
SoundFiles.push(['US/Score/1-0 Philadelphia Phillies', 2]);
SoundFiles.push(['US/Score/1-0 Philadelphia Phillies I4 home', 1]);
SoundFiles.push(['US/Score/2-0 Chicago Cubs', 1]);
SoundFiles.push(['US/Score/2-0 Chicago Cubs I2', 1]);
SoundFiles.push(['US/Score/2-0 Chicago Cubs I3 home', 1]);
SoundFiles.push(['US/Score/2-0 Minnesota Twins', 1]);
SoundFiles.push(['US/Score/2-0 Minnesota Twins Philadelphia Phillies', 1]);
SoundFiles.push(['US/Score/2-0 Minnesota Twins Philadelphia Phillies I4 home', 1]);
SoundFiles.push(['US/Score/2-0 Philadelphia Phillies', 1]);
SoundFiles.push(['US/Score/2-0 Pittsburgh Pirates', 1]);
SoundFiles.push(['US/Score/2-1', 1]);
SoundFiles.push(['US/Score/2-1 Boston Red Sox I4 home', 1]);
SoundFiles.push(['US/Score/2-1 Philadelphia Phillies', 2]);
SoundFiles.push(['US/Score/2-1 Philadelphia Phillies I5', 1]);
SoundFiles.push(['US/Score/2-1 Philadelphia Phillies Toronto Blue Jays', 1]);
SoundFiles.push(['US/Score/2-1 Philadelphia Phillies Toronto Blue Jays I5 away', 1]);
SoundFiles.push(['US/Score/2-1 Pittsburgh Pirates', 1]);
SoundFiles.push(['US/Score/2-1 Pittsburgh Pirates Philadelphia Phillies', 1]);
SoundFiles.push(['US/Score/5-3 Philadelphia Phillies', 2]);
SoundFiles.push(['US/Strikeouts/3K', 1]);
SoundFiles.push(['US/Strikeouts/4K', 1]);
SoundFiles.push(['US/Strikeouts/5K', 1]);
SoundFiles.push(['US/Strikeouts/7K', 1]);
SoundFiles.push(['US/WP 3B', 1]);
SoundFiles.push(['WP', 1]);
