SoundFiles = new Array;
SoundCounts = new Array;
SoundFiles.push('1-3');
SoundCounts.push([4, 2, 0]);
SoundFiles.push('1-4-3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('1B');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('1B 6-3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('1B F7');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('1B F8');
SoundCounts.push([1, 0, 1]);
SoundFiles.push('1B F9');
SoundCounts.push([2, 1, 0]);
SoundFiles.push('1B G5');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('1B G6');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('1B G7');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('1B G8');
SoundCounts.push([5, 0, 0]);
SoundFiles.push('1B G9');
SoundCounts.push([3, 0, 1]);
SoundFiles.push('1B L7');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('1B L8');
SoundCounts.push([3, 4, 0]);
SoundFiles.push('1B L9');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('2B');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('2B F7');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('2B F8');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('2B F9');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('2B G7');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('2B G9');
SoundCounts.push([1, 0, 1]);
SoundFiles.push('2B L7');
SoundCounts.push([1, 1, 1]);
SoundFiles.push('2B L8');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('2B L9');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('3-1');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('3B');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('3B F7');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('3B G9');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('3U');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('4-1');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('4-3');
SoundCounts.push([2, 1, 0]);
SoundFiles.push('4-3 O3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('5-3');
SoundCounts.push([8, 0, 0]);
SoundFiles.push('6-3');
SoundCounts.push([2, 0, 1]);
SoundFiles.push('Alternate Play Calls/1B G8');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Alternate Play Calls/1B L7');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Alternate Play Calls/1B L9 Alt');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Alternate Play Calls/1home (not great) alt');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Alternate Play Calls/4-3 Old');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Alternate Play Calls/6-3 orig');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Alternate Play Calls/F7 alt');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Alternate Play Calls/GIDP 4-6-3 alt');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Alternate Play Calls/K');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Alternate Play Calls/L8 alt2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Alternate Play Calls/Out1 alt');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Alternate Play Calls/Out3 alt');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Average/140');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Average/242');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Average/249');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Average/250');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Average/258');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Average/268');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Average/273');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('Average/282');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('Average/310');
SoundCounts.push([1, 0, 1]);
SoundFiles.push('Average/311');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Average/316');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('Average/323');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Average/333');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Average/337');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Average/350');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('BA');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Batters/453562');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Batters/465753');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Batters/467793');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Batters/514917');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Batters/546318');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Batters/546318 Lead');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Batters/571437');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Batters/571437 Lead');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Batters/592826');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Batters/592826 Lead');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Batters/595751');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Batters/596748');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Batters/596748 Lead');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Batters/608384');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Batters/608384 Lead');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Batters/656555');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Batters/664068');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Batters/664068 Lead');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('BB');
SoundCounts.push([9, 0, 1]);
SoundFiles.push('BB 4');
SoundCounts.push([4, 0, 0]);
SoundFiles.push('BB High');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('BB Inside');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Beginning of inning (not coded)/4Bottom');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Beginning of inning (not coded)/4Bottom 2-1');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Beginning of inning (not coded)/4Bottom 2-1 Boston Red Sox');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Beginning of inning (not coded)/4Bottom 2-1 Pittsburgh Pirates');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Bell');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('BI');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('BK');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('Count/0-1');
SoundCounts.push([3, 1, 0]);
SoundFiles.push('Count/0-1 Called');
SoundCounts.push([2, 0, 1]);
SoundFiles.push('Count/0-1 Called FT');
SoundCounts.push([1, 0, 1]);
SoundFiles.push('Count/0-1 Called SI');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/0-1 Foul');
SoundCounts.push([4, 0, 3]);
SoundFiles.push('Count/0-1 Foul Bunt');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/0-1 Swinging');
SoundCounts.push([2, 1, 0]);
SoundFiles.push('Count/0-1 Swinging SI');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/0-2');
SoundCounts.push([4, 0, 0]);
SoundFiles.push('Count/0-2 Called');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/0-2 Foul');
SoundCounts.push([6, 0, 0]);
SoundFiles.push('Count/0-2 Foul X');
SoundCounts.push([2, 0, 1]);
SoundFiles.push('Count/0-2 Swinging');
SoundCounts.push([1, 3, 2]);
SoundFiles.push('Count/0-2 Swinging SI');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-0');
SoundCounts.push([6, 0, 0]);
SoundFiles.push('Count/1-0 Ball High');
SoundCounts.push([4, 1, 3]);
SoundFiles.push('Count/1-0 Ball High FT');
SoundCounts.push([1, 0, 1]);
SoundFiles.push('Count/1-0 Ball High Very');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-0 Ball Inside');
SoundCounts.push([4, 2, 0]);
SoundFiles.push('Count/1-0 Ball Inside Very');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-0 Ball Low');
SoundCounts.push([6, 2, 3]);
SoundFiles.push('Count/1-0 Ball Low Dirt');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-0 Ball Low Inside');
SoundCounts.push([2, 0, 1]);
SoundFiles.push('Count/1-0 Ball Low Outside');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Count/1-0 Ball Low SI');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-0 Ball Outside');
SoundCounts.push([3, 0, 1]);
SoundFiles.push('Count/1-1');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Count/1-1 Ball High');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Count/1-1 Ball High FT');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-1 Ball High Outside');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-1 Ball Inside');
SoundCounts.push([3, 1, 1]);
SoundFiles.push('Count/1-1 Ball Low');
SoundCounts.push([2, 1, 0]);
SoundFiles.push('Count/1-1 Ball Outside');
SoundCounts.push([4, 2, 1]);
SoundFiles.push('Count/1-1 Called');
SoundCounts.push([1, 1, 2]);
SoundFiles.push('Count/1-1 Called CU');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-1 Foul');
SoundCounts.push([5, 1, 3]);
SoundFiles.push('Count/1-1 Foul Bunt');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-1 Swinging');
SoundCounts.push([1, 2, 1]);
SoundFiles.push('Count/1-1 Swinging CH');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-1 Swinging CU');
SoundCounts.push([1, 0, 1]);
SoundFiles.push('Count/1-2');
SoundCounts.push([5, 0, 0]);
SoundFiles.push('Count/1-2 Ball High');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-2 Ball High Inside');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-2 Ball High Inside FT');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-2 Ball High Very');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Count/1-2 Ball Inside');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Count/1-2 Ball Inside Very');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-2 Ball Low');
SoundCounts.push([2, 1, 0]);
SoundFiles.push('Count/1-2 Ball Low Dirt');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Count/1-2 Ball Low Dirt CU');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-2 Ball Low Outside');
SoundCounts.push([1, 0, 1]);
SoundFiles.push('Count/1-2 Ball Outside');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('Count/1-2 Ball Outside FT');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-2 Called');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('Count/1-2 Foul');
SoundCounts.push([6, 3, 2]);
SoundFiles.push('Count/1-2 Foul Bunt');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-2 Foul Tip');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/1-2 Foul X');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('Count/1-2 Swinging');
SoundCounts.push([2, 1, 0]);
SoundFiles.push('Count/2-0');
SoundCounts.push([5, 0, 0]);
SoundFiles.push('Count/2-0 Ball');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-0 Ball High');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Count/2-0 Ball High Inside Very');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-0 Ball Inside');
SoundCounts.push([2, 0, 1]);
SoundFiles.push('Count/2-0 Ball Low');
SoundCounts.push([2, 0, 1]);
SoundFiles.push('Count/2-0 Ball Low Dirt');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-0 Ball Low Outside');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-0 Ball Outside');
SoundCounts.push([2, 1, 1]);
SoundFiles.push('Count/2-1');
SoundCounts.push([5, 0, 0]);
SoundFiles.push('Count/2-1 Ball High');
SoundCounts.push([8, 0, 1]);
SoundFiles.push('Count/2-1 Ball High Inside');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-1 Ball High Inside CU');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-1 Ball Inside');
SoundCounts.push([2, 1, 0]);
SoundFiles.push('Count/2-1 Ball Inside Very');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-1 Ball Low');
SoundCounts.push([2, 1, 1]);
SoundFiles.push('Count/2-1 Ball Low Dirt');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-1 Ball Low Inside');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-1 Ball Outside');
SoundCounts.push([2, 0, 1]);
SoundFiles.push('Count/2-1 Ball Outside Very');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-1 Called');
SoundCounts.push([3, 1, 1]);
SoundFiles.push('Count/2-1 Foul');
SoundCounts.push([2, 0, 2]);
SoundFiles.push('Count/2-1 Swinging');
SoundCounts.push([2, 1, 0]);
SoundFiles.push('Count/2-2');
SoundCounts.push([5, 0, 0]);
SoundFiles.push('Count/2-2 Ball High');
SoundCounts.push([2, 1, 0]);
SoundFiles.push('Count/2-2 Ball High FT');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-2 Ball Inside CH');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-2 Ball Inside FT');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-2 Ball Low');
SoundCounts.push([3, 0, 1]);
SoundFiles.push('Count/2-2 Ball Low Dirt');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Count/2-2 Ball Low Inside');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Count/2-2 Ball Low Outside');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-2 Ball Outside');
SoundCounts.push([2, 3, 0]);
SoundFiles.push('Count/2-2 Called');
SoundCounts.push([1, 1, 1]);
SoundFiles.push('Count/2-2 Called FT');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-2 Foul');
SoundCounts.push([1, 2, 2]);
SoundFiles.push('Count/2-2 Foul Bunt');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/2-2 Foul X');
SoundCounts.push([1, 3, 1]);
SoundFiles.push('Count/2-2 Swinging');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('Count/2-2 Swinging FT');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-0');
SoundCounts.push([7, 0, 0]);
SoundFiles.push('Count/3-0 Ball High');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-0 Ball Inside');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-0 Ball Low');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Count/3-0 Ball Low Outside');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-1');
SoundCounts.push([9, 0, 0]);
SoundFiles.push('Count/3-1 Ball High');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-1 Ball High Outside');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-1 Ball High Very');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('Count/3-1 Ball Inside');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-1 Ball Low');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-1 Ball Outside');
SoundCounts.push([2, 0, 1]);
SoundFiles.push('Count/3-1 Called');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-1 Called FT');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-1 Foul');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-1 Low Inside');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-2');
SoundCounts.push([6, 0, 0]);
SoundFiles.push('Count/3-2 Ball');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('Count/3-2 Ball High');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Count/3-2 Ball High Outside');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-2 Ball Inside');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-2 Ball Low');
SoundCounts.push([1, 1, 1]);
SoundFiles.push('Count/3-2 Ball Low Dirt');
SoundCounts.push([3, 1, 0]);
SoundFiles.push('Count/3-2 Ball Outside');
SoundCounts.push([3, 1, 0]);
SoundFiles.push('Count/3-2 Called');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Count/3-2 Foul');
SoundCounts.push([5, 0, 1]);
SoundFiles.push('Count/3-2 Foul FT');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Count/3-2 Foul X');
SoundCounts.push([1, 1, 2]);
SoundFiles.push('CS');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('DP 1-2-3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('DP 5-4-3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('DP 6-4');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('DS2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('E');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('E5');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('E6');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('F7');
SoundCounts.push([6, 1, 0]);
SoundFiles.push('F8');
SoundCounts.push([6, 1, 0]);
SoundFiles.push('F8 O1');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('F9');
SoundCounts.push([9, 0, 1]);
SoundFiles.push('F9 O1');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('FC');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('FC 3-4');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('FC 5-6-4');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('FC 6-4');
SoundCounts.push([1, 0, 1]);
SoundFiles.push('FC 6-5');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('FC 9-4');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GameOver Atlanta Braves');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GameOver Boston Red Sox');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GameOver Colorado Rockies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GameOver Florida Marlins');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GameOver Houston Astros');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GameOver New York Mets');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GameOver Philadelphia Phillies');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('GameOver Philadelphia Phillies 11-10');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GameOver Philadelphia Phillies 2-1');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GameOver Philadelphia Phillies 5-3');
SoundCounts.push([2, 1, 1]);
SoundFiles.push('GameOver Philadelphia Phillies 8-7');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GameOver Pittsburgh Pirates');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GameOver San Diego Padres');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GameOver Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GameOver Washington Nationals 1-0');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GameOver Washington Nationals 11-6');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GIDP 1-2-3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GIDP 1-6-3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GIDP 4-3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GIDP 4-6-3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GIDP 5-4-3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GIDP 6-3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GIDP 6-4');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GIDP 6-4-3');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('GRD');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('GRD F7');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('HBP');
SoundCounts.push([2, 0, 1]);
SoundFiles.push('HighHopes');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('HomeOut');
SoundCounts.push([1, 0, 1]);
SoundFiles.push('HR');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('HR 7');
SoundCounts.push([4, 0, 0]);
SoundFiles.push('HR 8');
SoundCounts.push([1, 0, 2]);
SoundFiles.push('HR 9');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('IBB');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Inning/10away');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/10away B 7-7');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/10home');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/10home B');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/10home B 7-7');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/11away');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/11home');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/12away');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/1away E');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/1away E 0-0 Washington Nationals Philadelphia Phillies');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Inning/1away E 2-0 Chicago Cubs');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/1away E 3-0 Philadelphia Phillies Cincinnati Reds');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/1away E 5-0 Washington Nationals Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/1home 2-0 Chicago Cubs');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/1home B');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/1home E');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Inning/1home E 0-0');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/1home E 1-0 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/1home E 3-2 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/1home E 5-0 Washington Nationals Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2away');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2away 2-0 Chicago Cubs');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2away B');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2away B 1-0 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2away B 3-2 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2away E');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Inning/2away E 0-0 Philadelphia Phillies Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2away E 1-0 Philadelphia Phillies Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2away E 2-0 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2away E 3-2 Philadelphia Phillies Cincinnati Reds');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2home B');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Inning/2home B 1-0 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2home E');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Inning/2home E 0-0 Philadelphia Phillies Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2home E 0-0 Washington Nationals Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2home E 1-0 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2home E 2-0 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/2home E 5-0 Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/3away 2-0 Chicago Cubs');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/3away B');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Inning/3away B 1-0 Philadelphia Phillies');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Inning/3home');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/3home 2-0 Chicago Cubs');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/3home B');
SoundCounts.push([8, 0, 0]);
SoundFiles.push('Inning/3home B 0-0');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/3home B 1-0 Philadelphia Phillies');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Inning/3home B 2-0 Philadelphia Phillies New York Mets');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/3home B 5-0 Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/3home B 5-2 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/3home E');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Inning/3home E 0-0');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/3home E 1-0 Philadelphia Phillies');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Inning/3home E 5-0 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/3home E 5-1 Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/3home E 5-2 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/4away');
SoundCounts.push([4, 0, 0]);
SoundFiles.push('Inning/4away 1-0 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/4away 2-0 Minnesota Twins');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/4away 2-1 Boston Red Sox Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/4away 2-1 Pittsburgh Pirates Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/4home');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/4home 2-1 Pittsburgh Pirates Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/5away');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/5home');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/6away');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/6home');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/7away');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/7away 5-3 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/7away B');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/7away B 1-0 Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/7away B 6-6');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/7away E');
SoundCounts.push([5, 0, 0]);
SoundFiles.push('Inning/7away E 1-0 Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/7away E 8-5 Philadelphia Phillies New York Mets');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/7home');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/7home 5-3 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/7home B 6-3 Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/8away');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/8away B');
SoundCounts.push([4, 0, 0]);
SoundFiles.push('Inning/8away B 1-0 Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/8away B 1-1');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/8away B 6-6');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/8away B 7-6 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/8away B 8-5 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/8away E');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/8away E 6-6');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/8home');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/8home B');
SoundCounts.push([6, 0, 0]);
SoundFiles.push('Inning/8home B 1-0');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/8home B 1-0 Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/8home B 10-8 New York Mets');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/8home B 1-1');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/8home B 5-2 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/9away');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/9away B');
SoundCounts.push([9, 0, 0]);
SoundFiles.push('Inning/9away B 1-0 Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/9away B 1-0 Washington Nationals Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/9away B 10-9 New York Mets');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/9away B 10-9 New York Yankees');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/9away B 5-2  Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/9away B 5-2 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/9away B 6-6');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Inning/9away B 6-6 Philadelphia Phillies Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/9away B 6-6 Washington Nationals Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/9away B 7-7');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/9home');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/9home B');
SoundCounts.push([4, 0, 0]);
SoundFiles.push('Inning/9home B 10-9 New York Mets Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/9home B 11-6 Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/9home B 7-7');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Inning/extra innings');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('InPlay');
SoundCounts.push([1, 1, 1]);
SoundFiles.push('K');
SoundCounts.push([3, 5, 5]);
SoundFiles.push('K Foul Tip');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('K..');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('L3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('L4');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('L6');
SoundCounts.push([1, 0, 1]);
SoundFiles.push('L7');
SoundCounts.push([4, 0, 0]);
SoundFiles.push('L8');
SoundCounts.push([3, 1, 1]);
SoundFiles.push('L9');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Altherr');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Altherr Lead');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Asche');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Blanco, A');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Eickhoff');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Featherston');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Franco, M');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Galvis');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Galvis Lead');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Hellickson');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Hellickson Lead');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Hernandez, C');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Herrera');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Howard');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Joseph, T');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Joseph, T Lead');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Paredes Lead');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Ruiz');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Batters/2016Rupp');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Inning/4away');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Inning/7away');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('NEUTRAL/Inning/7home');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out1');
SoundCounts.push([10, 1, 2]);
SoundFiles.push('Out1 I2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out1 I3');
SoundCounts.push([2, 1, 0]);
SoundFiles.push('Out1 I7');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Out1 I8');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Out2');
SoundCounts.push([10, 2, 3]);
SoundFiles.push('Out2 I7');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out2 I9');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out3 Atlanta Braves');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out3 Chicago Cubs');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('Out3 Colorado Rockies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out3 Florida Marlins');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out3 Houston Astros');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out3 Miami Marlins');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out3 Minnesota Twins');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('Out3 New York Mets');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Out3 Philadelphia Phillies');
SoundCounts.push([7, 0, 1]);
SoundFiles.push('Out3 Philadelphia Phillies I1');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out3 Philadelphia Phillies I2');
SoundCounts.push([1, 0, 1]);
SoundFiles.push('Out3 Philadelphia Phillies I3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out3 Philadelphia Phillies I8');
SoundCounts.push([4, 0, 0]);
SoundFiles.push('Out3 Pittsburgh Pirates');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out3 San Diego Padres');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out3 St. Louis Cardinals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out3 Toronto Blue Jays');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('Out3 Washington Nationals');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Out3 Washington Nationals I2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Out3 Washington Nationals I3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('P2');
SoundCounts.push([4, 0, 1]);
SoundFiles.push('P3');
SoundCounts.push([1, 0, 1]);
SoundFiles.push('P4');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('P4 O2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('P5');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('P6');
SoundCounts.push([5, 0, 0]);
SoundFiles.push('P7');
SoundCounts.push([5, 0, 0]);
SoundFiles.push('P8');
SoundCounts.push([4, 0, 2]);
SoundFiles.push('P9');
SoundCounts.push([1, 1, 0]);
SoundFiles.push('PB');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('PC');
SoundCounts.push([4, 0, 0]);
SoundFiles.push('PC Cincinnati Reds');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('PC Florida Marlins');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('PC Philadelphia Phillies');
SoundCounts.push([4, 0, 0]);
SoundFiles.push('PC Toronto Blue Jays');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('PC Washington Nationals');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('PH');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Pitchers/J C Romero');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('PO');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('POA 1B');
SoundCounts.push([1, 3, 2]);
SoundFiles.push('POA 2B');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('PR');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('PR 2B');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Replay/Challenge');
SoundCounts.push([5, 0, 0]);
SoundFiles.push('Replay/Challenge Philadelphia Phillies');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Replay/Overturned');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Replay/Upheld');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/0000');
SoundCounts.push([10, 0, 2]);
SoundFiles.push('RHE/0001');
SoundCounts.push([4, 0, 0]);
SoundFiles.push('RHE/0100');
SoundCounts.push([2, 1, 0]);
SoundFiles.push('RHE/0101');
SoundCounts.push([9, 3, 4]);
SoundFiles.push('RHE/0101 Philadelphia Phillies (0) I8');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/0102');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('RHE/0103');
SoundCounts.push([4, 0, 0]);
SoundFiles.push('RHE/0103 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/0103 Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/0111');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/0112');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/0201');
SoundCounts.push([1, 1, 1]);
SoundFiles.push('RHE/0202');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('RHE/0203');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/0212');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/1100');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('RHE/1101');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/1102');
SoundCounts.push([1, 0, 1]);
SoundFiles.push('RHE/1111');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/1200');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/1201');
SoundCounts.push([2, 1, 0]);
SoundFiles.push('RHE/1202');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/1303');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/1402');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/2200');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/2202');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/2222');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/2301');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/2402');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/3201');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/3300');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/3302');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/3402');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/4210');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/4502');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/5511');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('RHE/5601');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/6600');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('RHE/I123');
SoundCounts.push([2, 4, 1]);
SoundFiles.push('RHE/I123 I8');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runners/0 O2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runners/1');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Runners/1 O1');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runners/1 O1 8I');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runners/2');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Runners/3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runners/3 O0');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runners/4');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runners/5');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Runners/5 O0');
SoundCounts.push([1, 0, 2]);
SoundFiles.push('Runners/5 O2');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Runners/6');
SoundCounts.push([2, 0, 1]);
SoundFiles.push('Runners/6 O0');
SoundCounts.push([2, 0, 2]);
SoundFiles.push('Runners/6 O0 I1 home');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runners/6 O2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runners/7');
SoundCounts.push([5, 0, 2]);
SoundFiles.push('Runners/7 O0');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Runners/7 O1');
SoundCounts.push([1, 0, 2]);
SoundFiles.push('Runners/7 O2');
SoundCounts.push([4, 0, 1]);
SoundFiles.push('Runs/Coming in to score');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runs/Coming in to score alt');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runs/It was an RBI');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runs/R1');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runs/R1 2B');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runs/R1 BB');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runs/R2');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Runs/R2 2B');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runs/R2 HR');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Runs/R3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runs/R3 2B');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Runs/R3 HR');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('SAC RBI');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('SAC_B');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('SB');
SoundCounts.push([1, 0, 1]);
SoundFiles.push('Score/0-0');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Score/0-0 Philadelphia Phillies Washington Nationals');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Score/1-0');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Score/1-0 Other Team Philadelphia Phillies');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Score/1-0 Philadelphia Phillies');
SoundCounts.push([10, 0, 2]);
SoundFiles.push('Score/1-0 Washington Nationals');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Score/10-10');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/10-2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/10-6');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/10-6 Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/10-8');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/10-8 New York Mets');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/10-9');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/10-9 New York Mets');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Score/10-9 New York Yankees');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/1-1');
SoundCounts.push([5, 0, 0]);
SoundFiles.push('Score/1-1 Philadelphia Phillies St. Louis Cardinals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/11-6');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/11-6 Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/13-1');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/2-0');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Score/2-0 Chicago Cubs');
SoundCounts.push([1, 1, 1]);
SoundFiles.push('Score/2-0 Other Team Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/2-0 Philadelphia Phillies');
SoundCounts.push([4, 0, 1]);
SoundFiles.push('Score/2-0 Philadelphia Phillies New York Mets');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/2-1 Other Team Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/2-1 Philadelphia Phillies');
SoundCounts.push([2, 0, 2]);
SoundFiles.push('Score/2-2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/3-0');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/3-2');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Score/3-2 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/3-2 Philadelphia Phillies Cincinnati Reds');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/3-3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/4-0');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/4-1 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/4-2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/4-2 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/5-0');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Score/5-0 Other Team Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/5-0 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/5-0 Washington Nationals');
SoundCounts.push([3, 0, 0]);
SoundFiles.push('Score/5-0 Washington Nationals Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/5-1 Other Team Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/5-1 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/5-2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/5-2 Philadelphia Phillies');
SoundCounts.push([7, 0, 0]);
SoundFiles.push('Score/5-3 Philadelphia Phillies');
SoundCounts.push([1, 0, 2]);
SoundFiles.push('Score/5-4');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/6-1 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/6-2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/6-3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/6-3 Other Team Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/6-3 Washington Nationals Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/6-4');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/6-4 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/6-4 Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/6-5');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/6-6');
SoundCounts.push([4, 0, 0]);
SoundFiles.push('Score/6-6 Philadelphia Phillies Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/7-1 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/7-2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/7-3');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/7-3 Other Team Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/7-4 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/7-6');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Score/7-6 Philadelphia Phillies');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Score/7-6 Philadelphia Phillies Washington Nationals');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/7-7');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/8-1');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/8-1 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/8-2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/8-4 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/8-5');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/8-5 Philadelphia Phillies');
SoundCounts.push([2, 0, 0]);
SoundFiles.push('Score/8-5 Philadelphia Phillies New York Mets');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/8-6');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/8-7');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/9-1');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/9-1 Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/9-2');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/9-5');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/9-5 Other Team Philadelphia Phillies');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/9-6');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Score/9-9');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('SF 8');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Stretch');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Stretch Harry');
SoundCounts.push([1, 0, 0]);
SoundFiles.push('Stretch pre-tune');
SoundCounts.push([1, 0, 0]);
SoundFiles.push(['WP', 1]);
